// Shared types for the application
// These mirror the Rust DTOs generated by tauri-specta

export interface Skill {
  id: string
  name: string
  description: string
  content: string
  type: "custom" | "system" | "marketplace" | "template"
  category: string | null
  tags: string[]
  version: number
  author: string
  format: "markdown" | "yaml" | "text"
  is_active: boolean
  is_template: boolean
  content_hash: string | null
  metadata: Record<string, unknown>
  created_at: string
  updated_at: string
}

export interface SkillVersion {
  id: string
  skill_id: string
  version: number
  content: string
  changelog: string
  created_at: string
}

export interface SkillDependency {
  id: string
  skill_id: string
  depends_on_id: string
  dep_type: "imports" | "extends" | "requires" | "conflicts"
  created_at: string
}

export interface Tool {
  id: string
  name: string
  display_name: string
  description: string
  install_path: string
  config_dir: string
  deploy_method: "symlink" | "copy" | "api"
  config_format: string
  version: string | null
  icon: string | null
  is_active: boolean
  last_detected: string | null
  created_at: string
  updated_at: string
}

export interface Deployment {
  id: string
  skill_id: string
  tool_id: string
  deploy_path: string | null
  deploy_method: "symlink" | "copy"
  status: "pending" | "active" | "syncing" | "error" | "outdated"
  version_deployed: number | null
  last_synced_at: string | null
  error_message: string | null
  deployed_at: string
}

export interface Project {
  id: string
  name: string
  path: string
  description: string
  tech_stack: string[]
  language: string | null
  framework: string | null
  is_active: boolean
  last_scanned_at: string | null
  created_at: string
  updated_at: string
}

export interface TestCase {
  id: string
  skill_id: string
  name: string
  description: string
  input_prompt: string
  expected_output: string | null
  actual_output: string | null
  status: "pending" | "running" | "passed" | "failed" | "error"
  score: number | null
  duration_ms: number | null
  model_used: string | null
  created_at: string
  updated_at: string
}

export interface MarketplaceItem {
  id: string
  source: string
  skill_name: string
  description: string
  author: string
  homepage_url: string | null
  stars: number
  downloads: number
  version: string | null
  category: string | null
  tags: string[]
  content_preview: string | null
  install_url: string | null
  content_hash: string | null
  last_refreshed: string
}

export interface UsageLog {
  id: string
  skill_id: string
  tool_id: string | null
  project_id: string | null
  action: string
  context: Record<string, unknown>
  timestamp: string
}

export interface GraphNode {
  id: string
  name: string
  category: string | null
  type: string
  version: number
}

export interface GraphEdge {
  source: string
  target: string
  type: string
}

export interface GraphDTO {
  nodes: GraphNode[]
  edges: GraphEdge[]
}

export interface ImpactAnalysis {
  skill_id: string
  direct_dependents: string[]
  transitive_dependents: string[]
  would_break_edges: string[]
  total_impacted: number
}

export interface TestResult {
  skill_id: string
  skill_name: string
  output: string
  score: number
  duration_ms: number
  model_used: string
  status: "passed" | "failed" | "error"
}

export interface OverviewStats {
  total_skills: number
  active_skills: number
  total_deployments: number
  connected_tools: number
  total_projects: number
  tests_run: number
}
